- name: get facts
  hosts: xfs_test
  become: yes
  tasks:
    - name: Gather ec2 facts
      action: ec2_facts

    - name: install xfsprogs 
      yum: name=xfsprogs state=latest 
    - name: Unmount filesystem
      mount: name=/data fstype=xfs state=unmounted

- name: make ext4
  hosts: xfs_test
  become: yes
  roles:
     - ansible-disk
  vars:
      disk_additional_disks:
      - disk: /dev/xvdb
        fstype: xfs
        force: yes
        mount_options: defaults
        mount: /data 
